# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table

# see: https://terraform-docs.io/user-guide/configuration/header-from
header-from: ../docs/header.md

# see: https://terraform-docs.io/user-guide/configuration/footer-from
footer-from: ../docs/footer.md

settings:
  hide-empty: true
  indent: 2

sort:
  enabled: true
  by: required

content: |-
  {{ .Header }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Footer }}
