# .github/workflows/terraform-ci.yml

name: "Terraform CI"

on:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main
  # Trigger the workflow on pull requests targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  terraform_fmt_check:
    name: "Terraform Format Check"
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform
      # This action installs a specific version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0 # Specify your desired Terraform version

      # Step 3: Initialize Terraform
      # This is good practice, especially if you add plan/validate steps later
      - name: Terraform Init
        run: terraform init

      # Step 4: Run the format check
      # The "-check" flag makes the command fail if files are not formatted
      - name: Terraform Fmt Check
        run: terraform fmt -check --recursive